CREATE APPLICATION PACKAGE if not exists ENRICHMENT_PACKAGE;
CREATE SCHEMA ENRICHMENT_PACKAGE.CODE_STAGE;
CREATE SCHEMA ENRICHMENT_PACKAGE.SHARE;
CREATE STAGE IF NOT EXISTS ENRICHMENT_PACKAGE.CODE_STAGE.APP;
GRANT USAGE ON SCHEMA ENRICHMENT_PACKAGE.SHARE TO SHARE IN APPLICATION PACKAGE ENRICHMENT_PACKAGE;
CREATE TABLE IF NOT EXISTS ENRICHMENT_PACKAGE.SHARE.METADATA(KEY STRING, VALUE OBJECT);
GRANT SELECT ON ENRICHMENT_PACKAGE.SHARE.METADATA TO SHARE IN APPLICATION PACKAGE ENRICHMENT_PACKAGE;



-- At this point, put all the files onto the stage ENRICHMENT_PACKAGE.CODE_STAGE.APP using either PUT or Snowsight
--INSTALLING APP 

ALTER APPLICATION PACKAGE ENRICHMENT_PACKAGE
  ADD VERSION ver1
  USING '@ENRICHMENT_PACKAGE.CODE_STAGE.APP';

CREATE APPLICATION ENRICHMENT_APP
  FROM APPLICATION PACKAGE ENRICHMENT_PACKAGE
  USING VERSION ver1;

CREATE OR REPLACE STREAMLIT CONNECTOR_MANAGER
ROOT_LOCATION = '@ENRICHMENT_PACKAGE.CODE_STAGE.APP'
MAIN_FILE = '/streamlit_app.py'
QUERY_WAREHOUSE = XS_WH;

-- For testing, creat a patch and upgrade app on provider side
ALTER APPLICATION PACKAGE ENRICHMENT_PACKAGE
 ADD PATCH FOR VERSION ver1
 USING '@ENRICHMENT_PACKAGE.CODE_STAGE.APP';

ALTER APPLICATION ENRICHMENT_APP
UPGRADE USING VERSION ver1;