USE ROLE ACCOUNTADMIN;
CREATE ROLE IF NOT EXISTS ZAMBONI_ROLE;

GRANT CREATE DATABASE ON ACCOUNT TO ROLE ZAMBONI_ROLE;
GRANT CREATE WAREHOUSE ON ACCOUNT TO ROLE ZAMBONI_ROLE;
GRANT ROLE ZAMBONI_ROLE TO USER <USER_NAME>;

USE ROLE ZAMBONI_ROLE;
CREATE WAREHOUSE XS_WH WAREHOUSE_SIZE = 'XSMALL';
CREATE DATABASE ZAMBONI_DB;

USE DATABASE ZAMBONI_DB;
CREATE SCHEMA ZAMBONI_METADATA;
CREATE SCHEMA ZAMBONI_SRC;
CREATE SCHEMA ZAMBONI_UTIL;
CREATE SCHEMA ZAMBONI_TGT;
CREATE SCHEMA ZAMBONI_TASKS;