USE ROLE ZAMBONI_ROLE;
USE WAREHOUSE XS_WH;

USE SCHEMA ZAMBONI_DB.ZAMBONI_METADATA;

CREATE OR REPLACE TABLE LABELS(
    LABEL_ID INT PRIMARY KEY 
    ,LABEL_NAME VARCHAR
    ,DESCRIPTION VARCHAR
    ,ATTRIBUTES VARIANT
    ,CREATED_TIMESTAMP TIMESTAMP_NTZ
    ,MODIFIED_TIMESTAMP TIMESTAMP_NTZ
);

CREATE OR REPLACE TABLE OBJECTS(
    OBJECT_ID INT PRIMARY KEY 
    ,OBJECT_TYPE VARCHAR
    ,DATABASE_NAME VARCHAR
    ,SCHEMA_NAME VARCHAR
    ,OBJECT_NAME VARCHAR
    ,ATTRIBUTES VARIANT
    ,LABELS ARRAY
    ,ADDED_TIMESTAMP TIMESTAMP_NTZ
    ,MODIFIED_TIMESTAMP TIMESTAMP_NTZ
);


CREATE OR REPLACE TABLE COLLECTIONS(
    COLLECTION_ID INT PRIMARY KEY
    ,COLLECTION_NAME VARCHAR
    ,COLLECTION_TYPE VARCHAR
    ,OBJECTS VARIANT
    ,LABELS ARRAY
    ,CREATED_TIMESTAMP TIMESTAMP_NTZ
    ,MODIFIED_TIMESTAMP TIMESTAMP_NTZ
);


CREATE OR REPLACE TABLE PROCESS_TYPES(
    PROCESS_TYPE_ID INT PRIMARY KEY
    ,PROCESS_TYPE VARCHAR
    ,DESCRIPTION VARCHAR
    ,TEMPLATE VARCHAR
    ,OBJECT_TYPE VARCHAR
    ,OBJECT_ACTION VARCHAR
    ,CREATED_TIMESTAMP TIMESTAMP_NTZ
    ,MODIFIED_TIMESTAMP TIMESTAMP_NTZ
);


CREATE OR REPLACE TABLE PROCESSES(
    PROCESS_ID INT PRIMARY KEY
    ,PROCESS_NAME VARCHAR
    ,PROCESS_TYPE_ID INT FOREIGN KEY REFERENCES ZAMBONI_DB.ZAMBONI_METADATA.PROCESS_TYPES (PROCESS_TYPE_ID)
    ,ATTRIBUTES VARIANT
    ,LABELS ARRAY
    ,CREATED_TIMESTAMP TIMESTAMP_NTZ
    ,MODIFIED_TIMESTAMP TIMESTAMP_NTZ
);


CREATE OR REPLACE TABLE PROCESS_DAG(
    PARENT_PROCESS_ID INT PRIMARY KEY
    ,PARENT_PROCESS_NAME VARCHAR
    ,CHILD_PROCESSES VARIANT
    ,LABELS ARRAY
    ,CREATED_TIMESTAMP TIMESTAMP_NTZ
    ,MODIFIED_TIMESTAMP TIMESTAMP_NTZ
);


CREATE OR REPLACE TABLE PROCESS_LOG(
    PROCESS_LOG_ID INT PRIMARY KEY
    ,PROCESS_RUN_ID INT 
    ,PARENT_PROCESS_ID INT
    ,PROCESS_ID INT FOREIGN KEY REFERENCES ZAMBONI_DB.ZAMBONI_METADATA.PROCESSES (PROCESS_ID)
    ,PROCESS_START_TIMESTAMP TIMESTAMP_NTZ
    ,PROCESS_END_TIMESTAMP TIMESTAMP_NTZ
    ,PROCESS_OUTPUT VARIANT
);