SET T2I_ROLE = CURRENT_ROLE();
SET T2I_DB = 'ICEBERG_MIGRATOR_DB';
SET T2I_SCH = 'ICEBERG_MIGRATOR_DB.ICEBERG_MIGRATOR';
SET T2I_WH = 'ICEBERG_MIGRATOR_WH';

USE ROLE IDENTIFIER($T2I_ROLE);

--create ICEBERG_MIGRATOR_DB database
CREATE DATABASE IF NOT EXISTS IDENTIFIER($T2I_DB);

--create ICEBERG_MIGRATOR schema
CREATE SCHEMA IF NOT EXISTS IDENTIFIER($T2I_SCH);

--create ICEBERG_MIGRATOR schema
CREATE SCHEMA IF NOT EXISTS ICEBERG_MIGRATOR_DB.STREAMLIT;

--create ICEBERG_STAGING schema
CREATE SCHEMA IF NOT EXISTS ICEBERG_MIGRATOR_DB.ICEBERG_STAGING;

--create ICEBERG_MIGRATOR_WH warehouse
CREATE WAREHOUSE IF NOT EXISTS IDENTIFIER($T2I_WH) WITH WAREHOUSE_SIZE = 'XSMALL'
  COMMENT = '{"origin": "sf_sit", "name": "table_to_iceberg", "version":{"major": 1, "minor": 2}}';

--create streamlit
USE SCHEMA ICEBERG_MIGRATOR_DB.STREAMLIT;
CREATE STAGE IF NOT EXISTS STREAMLIT;
CREATE STREAMLIT IF NOT EXISTS ICEBERG_MIGRATOR
  ROOT_LOCATION = '@ICEBERG_MIGRATOR_DB.STREAMLIT.STREAMLIT'
  MAIN_FILE = 'main.py'
  QUERY_WAREHOUSE = 'ICEBERG_MIGRATOR_WH'
  COMMENT = '{"origin":"sf_sit","name":"table_to_iceberg","version":{"major":1, "minor":2},"attributes":{"component":"table_to_iceberg","type":"streamlit"}}';


--unset vars
UNSET (T2I_ROLE, T2I_DB, T2I_SCH, T2I_WH);