SET major = 3;
SET minor = 2;
SET COMMENT = concat('{"origin": "sf_sit",
            "name": "evalanche",
            "version": {"major": ',$major,', "minor": ',$minor,'}}');

SET (streamlit_warehouse)=(SELECT CURRENT_WAREHOUSE());

CREATE DATABASE IF NOT EXISTS GENAI_UTILITIES
COMMENT = $COMMENT;

CREATE SCHEMA IF NOT EXISTS GENAI_UTILITIES.EVALUATION
COMMENT = $COMMENT;

CREATE OR ALTER TABLE GENAI_UTILITIES.EVALUATION.SAVED_EVALUATIONS
(EVAL_NAME VARCHAR,
DESCRIPTION VARCHAR,
METRIC_NAMES ARRAY,
SOURCE_SQL VARCHAR,
PARAM_ASSIGNMENTS VARIANT,
ASSOCIATED_OBJECTS VARIANT,
MODELS VARIANT)
COMMENT = $COMMENT;

CREATE OR ALTER TABLE GENAI_UTILITIES.EVALUATION.AUTO_EVALUATIONS
(EVAL_NAME VARCHAR,
DESCRIPTION VARCHAR,
METRIC_NAMES ARRAY,
SOURCE_SQL VARCHAR,
PARAM_ASSIGNMENTS VARIANT,
ASSOCIATED_OBJECTS VARIANT,
MODELS VARIANT)
COMMENT = $COMMENT;

CREATE OR ALTER TABLE GENAI_UTILITIES.EVALUATION.CUSTOM_METRICS
(METRIC_NAME VARCHAR,
STAGE_FILE_PATH VARCHAR,
CREATED_DATETIME TIMESTAMP,
SHOW_METRIC BOOLEAN,
CREATION_USER VARCHAR)
COMMENT = $COMMENT;

-- Create stage for App logic
CREATE STAGE IF NOT EXISTS GENAI_UTILITIES.EVALUATION.STREAMLIT_STAGE
DIRECTORY = (ENABLE = true)
COMMENT = $COMMENT;

PUT file://src.zip @GENAI_UTILITIES.EVALUATION.STREAMLIT_STAGE OVERWRITE = TRUE AUTO_COMPRESS = FALSE;
PUT file://src/*.py @GENAI_UTILITIES.EVALUATION.STREAMLIT_STAGE/src/ OVERWRITE = TRUE AUTO_COMPRESS = FALSE;
PUT file://home.py @GENAI_UTILITIES.EVALUATION.STREAMLIT_STAGE/ OVERWRITE = TRUE AUTO_COMPRESS = FALSE;
PUT file://environment.yml @GENAI_UTILITIES.EVALUATION.STREAMLIT_STAGE/ OVERWRITE = TRUE AUTO_COMPRESS = FALSE;
PUT file://pages/*.py @GENAI_UTILITIES.EVALUATION.STREAMLIT_STAGE/pages/ OVERWRITE = TRUE AUTO_COMPRESS = FALSE;

-- Helper SPROC to remove custom_metrics
CREATE OR REPLACE PROCEDURE GENAI_UTILITIES.EVALUATION.DELETE_METRIC(metric_name string)
RETURNS STRING
LANGUAGE PYTHON
IMPORTS = ('@GENAI_UTILITIES.EVALUATION.STREAMLIT_STAGE/src/sproc_utils.py')
PACKAGES = ('snowflake-snowpark-python')
RUNTIME_VERSION = '3.9'
HANDLER = 'sproc_utils.delete_metric'
COMMENT = $COMMENT;

-- Cortex Analyst runner
CREATE OR REPLACE PROCEDURE GENAI_UTILITIES.EVALUATION.CORTEX_ANALYST_SQL(prompt STRING, semantic_file_path STRING)
RETURNS STRING
LANGUAGE PYTHON
IMPORTS = ('@GENAI_UTILITIES.EVALUATION.STREAMLIT_STAGE/src/sproc_utils.py')
PACKAGES = ('snowflake-snowpark-python')
RUNTIME_VERSION = '3.9'
HANDLER = 'sproc_utils.cortex_analyst_runner'
COMMENT = $COMMENT;

-- Create Streamlit
CREATE OR REPLACE STREAMLIT GENAI_UTILITIES.EVALUATION.EVALUATION_APP
ROOT_LOCATION = '@GENAI_UTILITIES.EVALUATION.STREAMLIT_STAGE'
MAIN_FILE = 'home.py'
TITLE = "Evalanche: GenAI Evaluation Application"
QUERY_WAREHOUSE = $streamlit_warehouse
COMMENT = $COMMENT;
