SET major = 3;
SET minor = 2;
SET COMMENT = concat('{"origin": "sf_sit",
            "name": "evalanche",
            "version": {"major": ',$major,', "minor": ',$minor,'}}');

SET (streamlit_warehouse)=(SELECT CURRENT_WAREHOUSE());

CREATE DATABASE IF NOT EXISTS GENAI_UTILITIES
COMMENT = $COMMENT;

CREATE SCHEMA IF NOT EXISTS GENAI_UTILITIES.EVALUATION
COMMENT = $COMMENT;

-- Create API Integration for Git
CREATE OR REPLACE API INTEGRATION git_api_integration_snowflake_labs_emerging_solutions_toolbox
  API_PROVIDER = git_https_api
  API_ALLOWED_PREFIXES = ('https://github.com/Snowflake-Labs')
  ENABLED = TRUE;

-- Create Git Repository
CREATE OR REPLACE GIT REPOSITORY GENAI_UTILITIES.EVALUATION.git_evalanche
  API_INTEGRATION = git_api_integration_snowflake_labs_emerging_solutions_toolbox
  ORIGIN = 'https://github.com/Snowflake-Labs/emerging-solutions-toolbox.git';

ALTER GIT REPOSITORY GENAI_UTILITIES.EVALUATION.git_evalanche FETCH;

CREATE OR ALTER TABLE GENAI_UTILITIES.EVALUATION.SAVED_EVALUATIONS
(EVAL_NAME VARCHAR,
DESCRIPTION VARCHAR,
METRIC_NAMES ARRAY,
SOURCE_SQL VARCHAR,
PARAM_ASSIGNMENTS VARIANT,
ASSOCIATED_OBJECTS VARIANT,
MODELS VARIANT)
COMMENT = $COMMENT;

CREATE OR ALTER TABLE GENAI_UTILITIES.EVALUATION.AUTO_EVALUATIONS
(EVAL_NAME VARCHAR,
DESCRIPTION VARCHAR,
METRIC_NAMES ARRAY,
SOURCE_SQL VARCHAR,
PARAM_ASSIGNMENTS VARIANT,
ASSOCIATED_OBJECTS VARIANT,
MODELS VARIANT)
COMMENT = $COMMENT;

CREATE OR ALTER TABLE GENAI_UTILITIES.EVALUATION.CUSTOM_METRICS
(METRIC_NAME VARCHAR,
STAGE_FILE_PATH VARCHAR,
CREATED_DATETIME TIMESTAMP,
SHOW_METRIC BOOLEAN,
CREATION_USER VARCHAR)
COMMENT = $COMMENT;

-- Create stage for App logic
CREATE STAGE IF NOT EXISTS GENAI_UTILITIES.EVALUATION.STREAMLIT_STAGE
DIRECTORY = (ENABLE = true)
COMMENT = $COMMENT;

-- Copy Files from Git Repository into App Stage
COPY FILES
  INTO @GENAI_UTILITIES.EVALUATION.STREAMLIT_STAGE
  FROM @GENAI_UTILITIES.EVALUATION.git_evalanche/branches/main/framework-evalanche/
  FILES=('src.zip');

COPY FILES
  INTO @GENAI_UTILITIES.EVALUATION.STREAMLIT_STAGE/src/
  FROM @GENAI_UTILITIES.EVALUATION.git_evalanche/branches/main/framework-evalanche/src/
  PATTERN='.*[.]py';

COPY FILES
  INTO @GENAI_UTILITIES.EVALUATION.STREAMLIT_STAGE
  FROM @GENAI_UTILITIES.EVALUATION.git_evalanche/branches/main/framework-evalanche/
  FILES=('home.py', 'environment.yml');

COPY FILES
  INTO @GENAI_UTILITIES.EVALUATION.STREAMLIT_STAGE/pages/
  FROM @GENAI_UTILITIES.EVALUATION.git_evalanche/branches/main/framework-evalanche/pages/
  PATTERN='.*[.]py';

-- Helper SPROC to remove custom_metrics
CREATE OR REPLACE PROCEDURE GENAI_UTILITIES.EVALUATION.DELETE_METRIC(metric_name string)
RETURNS STRING
LANGUAGE PYTHON
IMPORTS = ('@GENAI_UTILITIES.EVALUATION.STREAMLIT_STAGE/src/sproc_utils.py')
PACKAGES = ('snowflake-snowpark-python')
RUNTIME_VERSION = '3.9'
HANDLER = 'sproc_utils.delete_metric'
COMMENT = $COMMENT;

-- Cortex Analyst runner
CREATE OR REPLACE PROCEDURE GENAI_UTILITIES.EVALUATION.CORTEX_ANALYST_SQL(prompt STRING, semantic_file_path STRING)
RETURNS STRING
LANGUAGE PYTHON
IMPORTS = ('@GENAI_UTILITIES.EVALUATION.STREAMLIT_STAGE/src/sproc_utils.py')
PACKAGES = ('snowflake-snowpark-python')
RUNTIME_VERSION = '3.9'
HANDLER = 'sproc_utils.cortex_analyst_runner'
COMMENT = $COMMENT;

-- Create Streamlit
CREATE OR REPLACE STREAMLIT GENAI_UTILITIES.EVALUATION.EVALUATION_APP
ROOT_LOCATION = '@GENAI_UTILITIES.EVALUATION.STREAMLIT_STAGE'
MAIN_FILE = 'home.py'
TITLE = "Evalanche: GenAI Evaluation Application"
QUERY_WAREHOUSE = $streamlit_warehouse
COMMENT = $COMMENT;
