local_key_path = "<path to your local RSA key, if set up>"

[account_1]
user = "<Snowflake Username>"
password = "<Snowflake password, if not using key/pair>"
role = "ACCOUNTADMIN"
account = "<Account Identifier>"
database = "SCAD_PACKAGE"
schema = "ADMIN"
warehouse = "scad_wh"
